//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitySchedule
    {
        public int ID { get; set; }
        public int ActivityID { get; set; }
        public Nullable<System.DateTime> ActivityStartDatetime { get; set; }
        public Nullable<System.DateTime> ActivityEndDatetime { get; set; }
        public Nullable<System.DateTime> ActivityExpiryDate { get; set; }
        public Nullable<int> RecurrenceType { get; set; }
        public Nullable<int> RecurEvery { get; set; }
        public Nullable<bool> OnMonday { get; set; }
        public Nullable<bool> OnTuesday { get; set; }
        public Nullable<bool> OnWednesday { get; set; }
        public Nullable<bool> OnThursday { get; set; }
        public Nullable<bool> OnFriday { get; set; }
        public Nullable<bool> OnSaturday { get; set; }
        public Nullable<bool> OnSunday { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
