//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityVisitor
    {
        public int ID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> UserType { get; set; }
        public string IPAddress { get; set; }
        public string OtherInformation { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
