//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityRewards
    {
        public int ID { get; set; }
        public int ActivityID { get; set; }
        public System.Guid ProviderId { get; set; }
        public int TotalHours { get; set; }
        public int CaloriesPerHour { get; set; }
        public Nullable<int> Earnrewards { get; set; }
        public int Tapreq { get; set; }
        public Nullable<int> QRCodeID { get; set; }
        public Nullable<bool> BpFlag { get; set; }
        public Nullable<int> BonusPoints { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
