//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardsType
    {
        public RewardsType()
        {
            this.Reward = new HashSet<Reward>();
        }
    
        public int ID { get; set; }
        public int Type { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Reward> Reward { get; set; }
    }
}
