//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Council = new HashSet<Council>();
        }
    
        public int ID { get; set; }
        public string StateName { get; set; }
        public string StateDetail { get; set; }
    
        public virtual ICollection<Council> Council { get; set; }
    }
}
