//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReward
    {
        public UserReward()
        {
            this.UserRewardLog = new HashSet<UserRewardLog>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RewardPoint { get; set; }
        public Nullable<int> RedeemedtPoint { get; set; }
        public Nullable<int> BonusPoint { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual UserProfiles UserProfiles { get; set; }
        public virtual ICollection<UserRewardLog> UserRewardLog { get; set; }
    }
}
