//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ActivitiesLogExplorer
    {
        public Nullable<int> ActivityLogGroupID { get; set; }
        public int ID { get; set; }
        public Nullable<int> LogType { get; set; }
        public string Message { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<int> NotificationNumber { get; set; }
        public Nullable<int> LogActionID { get; set; }
        public string Value { get; set; }
        public Nullable<int> EmailSentNumber { get; set; }
        public Nullable<System.DateTime> LastSent { get; set; }
        public Nullable<int> LastNotificationType { get; set; }
        public string Expr1 { get; set; }
    }
}
