//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_EmailExplorer
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmailType { get; set; }
        public Nullable<int> EmailTemplateID { get; set; }
        public string EmailName { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string Emailcc { get; set; }
        public Nullable<bool> EmailIsHTML { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public string ModifiedBy { get; set; }
        public int ID { get; set; }
    }
}
