//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_FooterMenu
    {
        public int ID { get; set; }
        public int LinkID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string LinkValue { get; set; }
        public string LinkText { get; set; }
        public Nullable<int> LinkType { get; set; }
    }
}
