//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_RewardUserExplorer
    {
        public System.Guid UserID { get; set; }
        public Nullable<int> Title { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public System.Guid Expr1 { get; set; }
        public Nullable<int> RewardPoint { get; set; }
        public Nullable<int> RedeemedtPoint { get; set; }
        public Nullable<int> BonusPoint { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
