//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAssets
    {
        public int ID { get; set; }
        public string Filename { get; set; }
        public string Filetitle { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileType { get; set; }
        public byte[] FileStream { get; set; }
        public string Link { get; set; }
    }
}
