//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesLog
    {
        public int ID { get; set; }
        public Nullable<int> LogType { get; set; }
        public string ReferenceNumber { get; set; }
        public string Message { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string Value { get; set; }
        public Nullable<int> NotificationNumber { get; set; }
        public Nullable<int> ActivityLogGroupID { get; set; }
        public Nullable<int> LogActionID { get; set; }
        public Nullable<bool> EmailSent { get; set; }
    
        public virtual ActivitiesLogGroup ActivitiesLogGroup { get; set; }
    }
}
