//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityGrouping
    {
        public int ID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<bool> forMale { get; set; }
        public Nullable<bool> forFemale { get; set; }
        public Nullable<bool> forChildren { get; set; }
        public Nullable<int> AgeFrom { get; set; }
        public Nullable<int> AgeTo { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
