//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityEligibility
    {
        public int ID { get; set; }
        public int ActivityID { get; set; }
        public Nullable<bool> MedicareCard { get; set; }
        public Nullable<bool> Pensioner { get; set; }
        public Nullable<bool> HealthcareCard { get; set; }
        public Nullable<bool> CityofBoroondara { get; set; }
        public Nullable<bool> CityofYarra { get; set; }
        public Nullable<bool> HACC { get; set; }
        public string Note { get; set; }
        public string Assessment { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
