//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityContactDetail
    {
        public int ID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> Title { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> SuburbID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> AltTitle { get; set; }
        public string AltFirstName { get; set; }
        public string AltMiddleName { get; set; }
        public string AltLastName { get; set; }
        public string AltEmail { get; set; }
        public string AltAddress { get; set; }
        public Nullable<int> AltSuburbID { get; set; }
        public Nullable<int> AltStateID { get; set; }
        public Nullable<int> AltPostCode { get; set; }
        public string AltPhoneNumber { get; set; }
        public string AltMobileNumber { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
