//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicianTimetable
    {
        public int ID { get; set; }
        public int ClinicianID { get; set; }
        public Nullable<System.DateTime> StartDatetime { get; set; }
        public Nullable<System.DateTime> EndDatetime { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> RecurrenceType { get; set; }
        public Nullable<int> RecurEvery { get; set; }
        public Nullable<bool> OnMonday { get; set; }
        public Nullable<bool> OnTuesday { get; set; }
        public Nullable<bool> OnWednesday { get; set; }
        public Nullable<bool> OnThursday { get; set; }
        public Nullable<bool> OnFriday { get; set; }
        public Nullable<bool> OnSaturday { get; set; }
        public Nullable<bool> OnSunday { get; set; }
    }
}
