//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISDEntities : DbContext
    {
        public ISDEntities()
            : base("name=ISDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ActivitiesLog> ActivitiesLog { get; set; }
        public virtual DbSet<ActivitiesLogGroup> ActivitiesLogGroup { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityClinician> ActivityClinician { get; set; }
        public virtual DbSet<ActivityContactDetail> ActivityContactDetail { get; set; }
        public virtual DbSet<ActivityEligibility> ActivityEligibility { get; set; }
        public virtual DbSet<ActivityGrouping> ActivityGrouping { get; set; }
        public virtual DbSet<ActivityImage> ActivityImage { get; set; }
        public virtual DbSet<ActivityImageDetail> ActivityImageDetail { get; set; }
        public virtual DbSet<ActivityReferenceCode> ActivityReferenceCode { get; set; }
        public virtual DbSet<ActivityRewards> ActivityRewards { get; set; }
        public virtual DbSet<ActivitySchedule> ActivitySchedule { get; set; }
        public virtual DbSet<ActivityUserAttendance> ActivityUserAttendance { get; set; }
        public virtual DbSet<ActivityUserLog> ActivityUserLog { get; set; }
        public virtual DbSet<ActivityVisitor> ActivityVisitor { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Clinic> Clinic { get; set; }
        public virtual DbSet<Clinicians> Clinicians { get; set; }
        public virtual DbSet<ClinicianTimetable> ClinicianTimetable { get; set; }
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<Council> Council { get; set; }
        public virtual DbSet<CustomerContact> CustomerContact { get; set; }
        public virtual DbSet<EmailSetting> EmailSetting { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplate { get; set; }
        public virtual DbSet<FooterMenu> FooterMenu { get; set; }
        public virtual DbSet<KeyCollection> KeyCollection { get; set; }
        public virtual DbSet<Keyword> Keyword { get; set; }
        public virtual DbSet<Link> Link { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<ProviderLog> ProviderLog { get; set; }
        public virtual DbSet<ProviderProfiles> ProviderProfiles { get; set; }
        public virtual DbSet<ProviderSettings> ProviderSettings { get; set; }
        public virtual DbSet<Requirements> Requirements { get; set; }
        public virtual DbSet<Reward> Reward { get; set; }
        public virtual DbSet<RewardImage> RewardImage { get; set; }
        public virtual DbSet<RewardsDetails> RewardsDetails { get; set; }
        public virtual DbSet<RewardsType> RewardsType { get; set; }
        public virtual DbSet<Sponsor> Sponsor { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Suburb> Suburb { get; set; }
        public virtual DbSet<UserImage> UserImage { get; set; }
        public virtual DbSet<UserImageDetail> UserImageDetail { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
        public virtual DbSet<UserProfiles> UserProfiles { get; set; }
        public virtual DbSet<UserReference> UserReference { get; set; }
        public virtual DbSet<UserReward> UserReward { get; set; }
        public virtual DbSet<UserRewardLog> UserRewardLog { get; set; }
        public virtual DbSet<UserSavedList> UserSavedList { get; set; }
        public virtual DbSet<VoucherDetails> VoucherDetails { get; set; }
        public virtual DbSet<WebAssets> WebAssets { get; set; }
        public virtual DbSet<WebConfiguration> WebConfiguration { get; set; }
        public virtual DbSet<WeblLogAction> WeblLogAction { get; set; }
        public virtual DbSet<WebLog> WebLog { get; set; }
        public virtual DbSet<v_ActivitiesLogExplorer> v_ActivitiesLogExplorer { get; set; }
        public virtual DbSet<v_ActivityClinicianExplorer> v_ActivityClinicianExplorer { get; set; }
        public virtual DbSet<v_ActivityExpiryView> v_ActivityExpiryView { get; set; }
        public virtual DbSet<v_ActivityExplorer> v_ActivityExplorer { get; set; }
        public virtual DbSet<v_ActivityImageExplorer> v_ActivityImageExplorer { get; set; }
        public virtual DbSet<v_ActivityView> v_ActivityView { get; set; }
        public virtual DbSet<v_ActivityVisitorCount> v_ActivityVisitorCount { get; set; }
        public virtual DbSet<v_CategoryCount> v_CategoryCount { get; set; }
        public virtual DbSet<v_CategoryExplorer> v_CategoryExplorer { get; set; }
        public virtual DbSet<v_CouncilExplorer> v_CouncilExplorer { get; set; }
        public virtual DbSet<v_EmailExplorer> v_EmailExplorer { get; set; }
        public virtual DbSet<v_FooterMenu> v_FooterMenu { get; set; }
        public virtual DbSet<v_KeyCollectionView> v_KeyCollectionView { get; set; }
        public virtual DbSet<v_Menu> v_Menu { get; set; }
        public virtual DbSet<v_ProviderActivityCount> v_ProviderActivityCount { get; set; }
        public virtual DbSet<v_ProviderClinicians> v_ProviderClinicians { get; set; }
        public virtual DbSet<v_ProviderExplorer> v_ProviderExplorer { get; set; }
        public virtual DbSet<v_RewardExplorer> v_RewardExplorer { get; set; }
        public virtual DbSet<v_RewardUserExplorer> v_RewardUserExplorer { get; set; }
        public virtual DbSet<v_ScheduleCount> v_ScheduleCount { get; set; }
        public virtual DbSet<v_SuburbExplorer> v_SuburbExplorer { get; set; }
        public virtual DbSet<v_UserAttendanceView> v_UserAttendanceView { get; set; }
        public virtual DbSet<v_UserExplorer> v_UserExplorer { get; set; }
        public virtual DbSet<v_VoucherExplorer> v_VoucherExplorer { get; set; }
        public virtual DbSet<v_WebLogExplorer> v_WebLogExplorer { get; set; }
    }
}
