//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public int LinkID { get; set; }
        public Nullable<int> MenuType { get; set; }
    
        public virtual Link Link { get; set; }
    }
}
