//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public Sponsor()
        {
            this.Reward = new HashSet<Reward>();
            this.VoucherDetails = new HashSet<VoucherDetails>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public Nullable<decimal> PhoneNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ContractExpiry { get; set; }
    
        public virtual ICollection<Reward> Reward { get; set; }
        public virtual ICollection<VoucherDetails> VoucherDetails { get; set; }
    }
}
