//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public UserImage()
        {
            this.UserImageDetail = new HashSet<UserImageDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<int> StorageUsed { get; set; }
        public Nullable<int> FreeStorage { get; set; }
        public Nullable<int> ImageAmount { get; set; }
    
        public virtual UserImage UserImage1 { get; set; }
        public virtual UserImage UserImage2 { get; set; }
        public virtual ICollection<UserImageDetail> UserImageDetail { get; set; }
    }
}
