//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImageDetail
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> UserImageID { get; set; }
        public string Filename { get; set; }
        public string ImageTitle { get; set; }
        public Nullable<int> ImageType { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isPrimaryImage { get; set; }
        public Nullable<int> Filesize { get; set; }
        public byte[] ImageStream { get; set; }
    
        public virtual UserImage UserImage { get; set; }
    }
}
