//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfiles
    {
        public UserProfiles()
        {
            this.UserLog = new HashSet<UserLog>();
            this.UserReward = new HashSet<UserReward>();
            this.UserSavedList = new HashSet<UserSavedList>();
        }
    
        public string UserID { get; set; }
        public Nullable<int> Title { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<bool> Aggreement { get; set; }
        public Nullable<int> PreferredContact { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public Nullable<bool> AccountDeletion { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<UserLog> UserLog { get; set; }
        public virtual ICollection<UserReward> UserReward { get; set; }
        public virtual ICollection<UserSavedList> UserSavedList { get; set; }
    }
}
