//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ActivityExplorer
    {
        public int ID { get; set; }
        public virtual string Name { get; set; }
        public virtual string PhoneNumber { get; set; }
        public virtual Nullable<int> SuburbID { get; set; }
        public virtual Nullable<int> StateID { get; set; }
        public string Suburb { get; set; }
        public string ShortDescription { get; set; }
        public string StateName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CategoryLevel1ParentID { get; set; }
        public string CategoryLevel1ParentName { get; set; }
        public Nullable<int> CategoryLevel2ParentID { get; set; }
        public string CategoryLevel2ParentName { get; set; }
        public virtual string Address { get; set; }
        public virtual Nullable<int> PostCode { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> ActivityType { get; set; }
        public virtual string Keywords { get; set; }
        public string Website { get; set; }
        public virtual string Price { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public virtual string Email { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> Title { get; set; }
        public Nullable<int> AltTitle { get; set; }
        public string AltFirstName { get; set; }
        public string AltMiddleName { get; set; }
        public string AltLastName { get; set; }
        public string AltEmail { get; set; }
        public string AltAddress { get; set; }
        public Nullable<int> AltSuburbID { get; set; }
        public virtual Nullable<int> AltStateID { get; set; }
        public virtual Nullable<int> AltPostCode { get; set; }
        public string AltPhoneNumber { get; set; }
        public string AltMobileNumber { get; set; }
        public virtual string eligibilityDescription { get; set; }
        public virtual string FullDescription { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> TimetableSize { get; set; }
        public Nullable<int> TimetableType { get; set; }
        public Nullable<bool> Personalised { get; set; }
        public string ProviderName { get; set; }
        public string ProviderBranch { get; set; }
        public Nullable<int> AgeTo { get; set; }
        public Nullable<int> AgeFrom { get; set; }
        public Nullable<bool> forMale { get; set; }
        public Nullable<bool> forFemale { get; set; }
        public Nullable<bool> forChildren { get; set; }
        public Nullable<int> IsPaid { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<int> SecondaryCategoryID1 { get; set; }
        public Nullable<int> SecondaryCategoryID2 { get; set; }
        public Nullable<int> SecondaryCategoryID3 { get; set; }
        public Nullable<int> SecondaryCategoryID4 { get; set; }
        public string Council { get; set; }
        public Nullable<int> CouncilID { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<int> Visitor { get; set; }
        public string ProviderID { get; set; }
        public Nullable<bool> isPrimary { get; set; }
        public Nullable<int> PrimaryServiceID { get; set; }
    }
}
