//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CategoryExplorer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Level1ParentID { get; set; }
        public Nullable<int> Level2ParentID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> Activities { get; set; }
        public string Level1ParentName { get; set; }
        public string Level2ParentName { get; set; }
        public int Level { get; set; }
    }
}
