//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CouncilExplorer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StateID { get; set; }
        public string StateName { get; set; }
        public string StateDetail { get; set; }
    }
}
