//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ProviderClinicians
    {
        public int ID { get; set; }
        public string ProviderID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> TimetableType { get; set; }
        public Nullable<int> RecurEvery { get; set; }
        public Nullable<bool> OnMonday { get; set; }
        public Nullable<bool> OnTuesday { get; set; }
        public Nullable<bool> OnWednesday { get; set; }
        public Nullable<bool> OnThursday { get; set; }
        public Nullable<bool> OnFriday { get; set; }
        public Nullable<bool> OnSaturday { get; set; }
        public Nullable<bool> OnSunday { get; set; }
    }
}
