//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SubServiceExplorer
    {
        public string UserID { get; set; }
        public string ProviderName { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string ActivityCode { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SecondaryCategoryID1 { get; set; }
        public Nullable<int> SecondaryCategoryID4 { get; set; }
        public Nullable<int> SecondaryCategoryID3 { get; set; }
        public Nullable<int> SecondaryCategoryID2 { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public string Price { get; set; }
        public string eligibilityDescription { get; set; }
        public int Status { get; set; }
        public string Website { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> TimetableType { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> isPrimary { get; set; }
        public Nullable<int> PrimaryServiceID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> ActivityType { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
    }
}
