//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WebLogExplorer
    {
        public int LogID { get; set; }
        public Nullable<int> LogActionID { get; set; }
        public string Message { get; set; }
        public string Note { get; set; }
        public string ReferenceNumber { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> LogCategory { get; set; }
        public Nullable<int> ActionType { get; set; }
        public string ActionMessage { get; set; }
        public Nullable<int> ActionCategory { get; set; }
        public int Expr1 { get; set; }
    }
}
