//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherDetails
    {
        public int ID { get; set; }
        public string VoucherCode { get; set; }
        public int RewardID { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<bool> UsageStatus { get; set; }
        public string RewardName { get; set; }
        public System.Guid SponsorID { get; set; }
    
        public virtual Reward Reward { get; set; }
        public virtual Sponsor Sponsor { get; set; }
    }
}
