//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebConfiguration
    {
        public int ID { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDatetime { get; set; }
        public Nullable<bool> AdvancedSearch { get; set; }
        public string AdministratorSiteUrl { get; set; }
        public string CustomerSiteUrl { get; set; }
        public string ProviderSiteUrl { get; set; }
        public string ProviderImageUrl { get; set; }
        public string SMTPAccount { get; set; }
        public string SMTPPassword { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPHost { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public Nullable<bool> SMTPSSL { get; set; }
        public Nullable<bool> SMTPIIS { get; set; }
        public Nullable<bool> EnableCaptcha { get; set; }
        public Nullable<bool> EnableExpiryProcessing { get; set; }
        public Nullable<bool> EnableFirstNotification { get; set; }
        public Nullable<int> FirstNotificationDays { get; set; }
        public Nullable<bool> EnableSecondNotification { get; set; }
        public Nullable<int> SecondNotificationDays { get; set; }
        public Nullable<bool> SendNotificationEmail { get; set; }
        public Nullable<bool> EnableRewardProcessing { get; set; }
        public Nullable<int> PointsAwarded { get; set; }
    }
}
