//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.Data.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLog
    {
        public WebLog()
        {
            this.WeblLogAction = new HashSet<WeblLogAction>();
        }
    
        public int ID { get; set; }
        public string Message { get; set; }
        public Nullable<int> LogCategory { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string ReferenceNumber { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<WeblLogAction> WeblLogAction { get; set; }
    }
}
